#frase = str(input('Insira uma frase: '))
#numeroDea = frase.count('a')
#encontraPrimeiroA = frase.find('a')
#encontraUltimoA = frase.rfind('a')
#print(numeroDea)
#print(encontraPrimeiroA)
#print(encontraUltimoA)
frase = str(input('Insira uma frase: ')).upper()
print('A letra aparece {} vezes'.format(frase.count('A')))
print('A primeira letra A aparece na posição {}'.format(frase.find('A')))
print('A última letra A aparece na posição {}'.format(frase.rfind('A')))