n = input('Insira um valor: ')
print('O tipo primitivo desse valor é ', type(n))
print('É numérico? ', n.isnumeric())
print('É alfabético? ', n.isalpha())
print('É apenas espaços? ', n.isspace())
print('É alfanumérico? ', n.isalpha())
print('Está em maíusuclo?', n.isupper())
print('está em minúsuculo?', n.islower())
print('está capitalizada? ', n.istitle())